name: release

on:
  push:
    tags:
    - "v*"
    branches:
      - main
  pull_request:
    branches:  
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: Assets/Qbitz/Drone-OSC-Controller
    - run: find Assets/Qbitz/Drone-OSC-Controller -name \*.meta >> metaList
    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: Drone.OSC.Controller.${{ github.ref_name }}.unitypackage
        include-files: metaList
    - name: Upload Artifact Main
      if: ${{ github.ref_name == 'main' }}
      uses: actions/upload-artifact@v4
      with:
        path: Drone.OSC.Controller.${{ github.ref_name }}.${{ github.sha }}.unitypackage
        name: ${{ github.ref_name }}.${{ github.sha }}
    - name: Upload Artifact Version Tag
      if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
      uses: actions/upload-artifact@v4
      with:
        path: Drone.OSC.Controller.${{ github.ref_name }}.unitypackage
        name: ${{ github.ref_name }}
    - name: Upload binaries to release
      if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Drone.OSC.Controller.${{ github.ref_name }}.unitypackage
        tag: ${{ github.ref }}
