name: release

on:
  push:
    tags:
    - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: Assets/Qbitz/Drone-OSC-Controller
    - run: find Assets/Qbitz/Drone-OSC-Controller -name \*.meta >> metaList
    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: Drone.OSC.Controller.${{ github.ref_name }}.unitypackage
        include-files: metaList
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: Drone.OSC.Controller.${{ github.ref_name }}.unitypackage
        name: ${{ github.ref_name }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Drone.OSC.Controller.${{ github.ref_name }}.unitypackage
        tag: ${{ github.ref }}
